version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./init/1.sql:/docker-entrypoint-initdb.d/create_tables.sql

  api:
    image: user-api:0.1
    ports:
      - "8080:8080"

volumes:
  db:
    driver: local